[package]
name    = "lex-finance"
version = "0.1.0"
lex     = "0.9.7"
[dependencies]
lex-fix       = { path = "../lex-fix" }
lex-money     = { path = "../lex-money" }
lex-trade     = { path = "../lex-trade" }
lex-trail     = { path = "../lex-trail" }
lex-positions = { path = "../lex-positions" }
lex-orm       = { path = "../lex-orm" }
lex-risk      = { path = "../lex-risk" }
lex-sor       = { path = "../lex-sor" }
